### PR TITLE
Issue #12 Add support for latest android-emulator 3.0

### PR DESCRIPTION
**Pull request by lukzeg**
Basing on problems described in:
https://github.com/jenkinsci/open-stf-plugin/issues/12

We mostly can see, that the api in android-emulator 3.0 was changed. Also to be fully compatible, we need to switch to java-8 which is used for compiling plugins for jenkins with at least ver. 2.32.

It was tested together with latest ver of STF:
https://github.com/openstf/stf/commit/2dac3d1bbd1ef1974a1c22a10941c5739711928e

### CODE REVIEW

**Comment by hram** [comment]
@lukzeg how can I build plugin by myself?

**Comment by lukzeg** [comment]
hi @hram ,

The easiest way, it will be checkout code from my fork:
https://github.com/lukzeg/open-stf-plugin
cmd:
git clone https://github.com/lukzeg/open-stf-plugin.git

and inside project folder just run cmd:
mvn install

After build finish, you will find binaries under target folder:
open-stf.hpi

or you can use this binaries:

[jenkins_open_stf_plugin.tar.gz](https://github.com/jenkinsci/open-stf-plugin/files/1643051/jenkins_open_stf_plugin.tar.gz)

If you will have any problems let me know.

**Comment by hram** [comment]
@lukzeg I just install plugin from binary and its works!!!
thank you very much

**Comment by lukzeg** [comment]
You're welcome. 
Should I create pull request which contain only one commit instead of 6 on my fork?

**Comment by justice3120** [comment]
@lukzeg 
That's not necessary.
I will release this as a new version.

**Pull request merged**
